name: publish

on:
  push:
    branches: ["main"]

jobs:
  docker-push:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: dytlzl
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build app
        uses: docker/build-push-action@v4
        with:
          context: .
          file: dockerfiles/dev.Dockerfile
          push: true
          load: false
          tags: ghcr.io/dytlzl/dynamite-compiler-dev:0.0.2
          platforms: linux/amd64,linux/arm/v7,linux/arm64
          cache-from: type=gha
          cache-to: type=gha,mode=max
